Add support eslint-plugin-no-unsanitized
jfmengels/eslint-rule-documentation pull request #16
Opened 2017-07-04 08:43 UTC by mozfreddyb

2017-07-10 17:52 UTC, j-f1 requested changes

2017-07-10 17:52 UTC, j-f1 commented on plugins.json
> +  "no-unsanitized": "https://github.com/mozilla/eslint-plugin-no-unsanitized/blob/master/docs/rules/no-unsanitized.md",
I think you want <code>.../docs/rules/**RULENAME**.md</code>, so it will automatically work if you add new rules.

2017-07-10 17:56 UTC, Arcanemagus commented on plugins.json
> +  "no-unsanitized": "https://github.com/mozilla/eslint-plugin-no-unsanitized/blob/master/docs/rules/no-unsanitized.md",
Additionally it looks like you need to split your documentation up a bit, as your rules are `method` and `property`.

2017-07-20 10:26 UTC, jonathanKingston commented on plugins.json
> +  "no-unsanitized": "https://github.com/mozilla/eslint-plugin-no-unsanitized/blob/master/docs/rules/no-unsanitized.md",
This work has now merged in: https://github.com/mozilla/eslint-plugin-no-unsanitized/pull/65

2017-07-20 16:49 UTC, Arcanemagus commented on plugins.json
> +  "no-unsanitized": "https://github.com/mozilla/eslint-plugin-no-unsanitized/blob/master/docs/rules/no-unsanitized.md",
Great news @jonathanKingston! Now this PR just needs to be updated as @j-f1 stated so the link will be automatically filled in 😉.

2017-07-20 19:24 UTC, mozfreddyb commented on plugins.json
> +  "no-unsanitized": "https://github.com/mozilla/eslint-plugin-no-unsanitized/blob/master/docs/rules/no-unsanitized.md",
Thanks! Done 👍

2017-07-20 19:25 UTC, mozfreddyb commented
Should be all good now.

2017-07-20 19:59 UTC, Arcanemagus approved these changes
LGTM, thanks!

2017-07-20 20:00 UTC, merged

2017-07-20 20:04 UTC, Arcanemagus commented
Published in v1.0.14. 🎉